# Generated by Django 4.0.2 on 2022-02-11 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pitanje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('znak', models.CharField(max_length=150)),
                ('tacan_odg', models.CharField(max_length=150)),
                ('netacan_odg1', models.CharField(max_length=150)),
                ('netacan_odg2', models.CharField(max_length=150)),
            ],
        ),
    ]
