# Generated by Django 4.0.2 on 2022-02-11 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Znaci', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pitanje',
            old_name='netacan_odg1',
            new_name='netacni_odg1',
        ),
        migrations.RenameField(
            model_name='pitanje',
            old_name='netacan_odg2',
            new_name='netacni_odg2',
        ),
    ]
